name: 'GitHub Container Build and Release'

on: workflow_dispatch
jobs:
  repo2docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      - uses: actions/checkout@v4
      
      - run: cat $HOME/.docker/config.json
      - uses: docker://docker
        with:
          entrypoint: docker
          args: info
      
      - uses: docker://docker
        with:
          entrypoint: docker
          args: login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      
      - run: cat $HOME/.docker/config.json
      - uses: docker://docker
        with:
          entrypoint: docker
          args: info
      
      - name: Build and Deploy
        id: docker
        uses: RepoDynamics/BinderDocker@v0.1
        with:
          image_name: ghcr.io/aariam/docker-test
          image_tags: latest
          git_ref: ${{ github.ref }}
          cache_image_tags: latest
          push: True
      
      - run: cat $HOME/.docker/config.json
      - uses: docker://docker
        with:
          entrypoint: docker
          args: info
      
      - name: Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/aariam/docker-test
          subject-digest: ${{ steps.docker.outputs.image_digest }}
          push-to-registry: 'true'
          show-summary: 'true'
      
      - name: Validation
        if: always()
        run: |
          docker logout
          image_names_str="${{ steps.docker.outputs.image_names }}"
          IFS=' ' read -r -a image_names <<< "$image_names_str"
          for image_name in "${image_names[@]}"; do
              echo "::group::Public Status Validation: ${image_name}"
              if docker pull "${image_name}"; then
                  echo "✅ ${image_name} is publicly visible."
              else
                  echo "::warning title=BinderDocker::Pushed image '${image_name}' is not publicly visible."
              fi
              echo "::endgroup::"
          done
