name: Test

on: workflow_dispatch
jobs:
  repo2docker:
    name: >-
      ${{ (matrix.env.DOCKER_CONFIG && 'env') || 'noenv' }} |
      ${{ matrix.first_login }} |
      ${{ (matrix.binderdocker_logout && 'logout') || 'nologout' }} |
      ${{ (matrix.second_login && 'login') || 'nologin' }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - DOCKER_CONFIG: $HOME/.docker
          - {}
        first_login:
          - login-action
          - binderdocker
          - both
        binderdocker_logout: [ true, false ]
        second_login: [ true, false ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        id: login-action-before
        if: matrix.first_login != 'binderdocker'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Deploy
        id: binder-docker
        uses: RepoDynamics/BinderDocker@main
        with:
          docker_registry: ${{ (matrix.first_login != 'login-action' && 'ghcr.io') || '' }}
          docker_username: ${{ (matrix.first_login != 'login-action' && github.repository_owner) || '' }}
          docker_password: ${{ (matrix.first_login != 'login-action' && secrets.GITHUB_TOKEN) || '' }}
          image_name: ghcr.io/aariam/docker-test
          image_tags: latest
          git_ref: ${{ github.ref }}
          cache_image_tags: latest
          push: True
          verify_public: ${{ (matrix.binderdocker_logout && 'warning') || 'false' }}
      - uses: docker/login-action@v3
        id: login-action-after
        if: matrix.second_login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Attestation
        id: attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/aariam/docker-test
          subject-digest: ${{ steps.binder-docker.outputs.image_digest }}
          push-to-registry: 'true'
          show-summary: 'false'
      - name: Summary
        if: always()
        env:
          job_steps: ${{ steps }}
        shell: python
        run: |
          import os
          import json
          
          step_summary = os.environ["GITHUB_STEP_SUMMARY"]
          steps = json.loads(os.environ["job_steps"])
          all_passed = True
          with open(step_summary, "a") as f:
            for step_id, step in steps.items():
              if step["outcome"] == "failure":
                print(f'❌ {step_id}', file=f)
                all_passed = False
            if all_passed:
              print('✅', file=f)
