name: Test docker/login-actions/issues/32

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      
      - run: cat $HOME/.docker/config.json
      - uses: docker://docker
        with:
          entrypoint: docker
          args: info
      
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - run: cat $HOME/.docker/config.json
      - uses: docker://docker
        with:
          entrypoint: docker
          args: info
