name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      -
        name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: docker://docker
        with:
          entrypoint: docker
          args: info
